services:
  jaguar:
   build: ..
   network: host
   environment: 
    - ROS_MASTER_URI=http://localhost:11311/
   command:  rosrun drrobot_jaguar4x4_player drrobot_jaguar4x4_player_node

  roscore:
   build: ..
   network: host
   environment: 
    - ROS_MASTER_URI=http://localhost:11311/
   command:  roscore