services:
  jaguar:
    build: ..
    network_mode: host
    ipc: host
    environment: 
      - ROS_MASTER_URI=http://localhost:11311/
    command:  bash -c "source devel/setup.bash && rosrun drrobot_jaguar4x4_player drrobot_jaguar4x4_player_node"

  roscore:
    build: ..
    network_mode: host
    ipc: host
    environment: 
      - ROS_MASTER_URI=http://localhost:11311/
    command:  roscore